import Head from 'next/head'
import ContainerRegisterEmpresa from '../../../components/Register/Register-Empresa/ContainerRegisterEmpresa.js'
import styles from '../../../styles/RegisterEmpresa.module.css'

export default function RegisterEmpresa() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Inmo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icono_inmo_corto.png" />
      </Head>
      <ContainerRegisterEmpresa />
      
    </div>
  )
}