import Head from 'next/head'
import ContainerInicioSesion from '../../components/InicioSesion/ContainerInicioSesion'
import styles from '../../styles/InicioMain.module.css'

export default function InicioMain() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Inmo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icono_inmo_corto.png" />
      </Head>
    <ContainerInicioSesion />
      
    </div>
  )
}