import Head from 'next/head'
import { useState } from 'react'
import ContainerInicioSesion from '../../components/InicioSesion/ContainerInicioSesion'
import styles from '../../styles/InicioMain.module.css'

export default function InicioMain() {

  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")


  return (
    <div className={styles.body}>
      <Head>
        <title>Inmo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icono_inmo_corto.png" />
      </Head>
    <ContainerInicioSesion 
      email={email}
      setEmail={setEmail}
      password={password}
      setPassword={setPassword}
    />
      
    </div>
  )
}