import Head from 'next/head'
import ContainerInicioSesion from '../../components/InicioSesion/ContainerInicioSesion'
import styles from '../../styles/InicioSesionMain.module.css'
import { useContext, useEffect, useState } from 'react'
import firebase, { FirebaseContext } from '../../firebase'
import { useRouter } from 'next/router'
import Layout from '../../components/layout/Layout'

export default function InicioMain() {


  const router = useRouter()

  const { usuario } = useContext(FirebaseContext)

  const [loadingBig, setLoadingBig] = useState(true)

  useEffect(() => {
    if (usuario != null) {
      console.log(usuario)
      if (Object.keys(usuario).length > 0) {
        setTimeout(() => {
          console.log("el usuario esta loggeado")
          router.push('/')
          return
        }, 3000)

      } else {
        console.log('no')
        setLoadingBig(false)
        return
      }

    }



  }, [usuario])


  return (
    <div className={styles.body_before}>
      <div className={styles.body}>
        <Head>
          <title>Inmo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icono_inmo_corto.png" />
        </Head>
        <Layout registro={true}>
          <ContainerInicioSesion loadingBig={loadingBig} />
        </Layout>

      </div>
    </div>

  )
}