import { doc, getDoc } from 'firebase/firestore'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect, useState } from 'react'
import ContainerRegisterParticular1 from '../../components/Register/Register-Particular/ContainerRegisterParticular1'
import ContainerRegisterParticular2 from '../../components/Register/Register-Particular/ContainerRegisterParticular2'
import ContainerRegisterParticular3 from '../../components/Register/Register-Particular/ContainerRegisterParticular3'
import ContainerSpinner from '../../components/Register/ContainerSpinner'
import firebase, { FirebaseContext } from '../../firebase'
import styles from '../../styles/RegisterParticular.module.css'
import Layout from '../../components/layout/Layout'











export default function RegisterParticular() {

  const [verdadero, setVerdadero] = useState(false)
  const [verdadero2, setVerdadero2] = useState(false)

  const [omitir, setOmitir] = useState(false)

  const [loadingBig, setLoadingBig] = useState(true)


  const [userCore, setUserCore] = useState({})

  const router = useRouter()

  const { usuario } = useContext(FirebaseContext)


  // Si el usuario ya subio una foto, que no pueda acceder a esta seccion




  useEffect(() => {
    // if (usuario != null) {
    //   console.log(usuario)
    //   if (Object.keys(usuario.usuario).length > 0) {
    //     console.log("el usuario ya existe")
    //     router.push('/')
    //     return
    //   }
    //   setLoadingBig(false)
    //   console.log('no')
    // }


    if (usuario != null) {
      console.log(usuario)
      if (Object.keys(usuario).length > 0) {
        console.log("el usuario esta loggeado")
        router.push('/')
        return
      }
      setLoadingBig(false)
      console.log('no')
      return
    }



  }, [usuario])





  return (
    <div className={styles.body_before}>
      <div className={styles.body}>
        <Head>
          <title>Inmo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo_inmo_new.png" />
        </Head>
        <Layout>
          {
            loadingBig == true ?
              <ContainerSpinner />
              :
              verdadero == false ?
                <ContainerRegisterParticular1
                  setVerdadero={setVerdadero}
                  userCore={userCore}
                  setUserCore={setUserCore}

                />
                :
                (
                  verdadero2 == false ?
                    <ContainerRegisterParticular2
                      setVerdadero={setVerdadero}
                      setVerdadero2={setVerdadero2}
                      userCore={userCore}
                      setUserCore={setUserCore}
                      omitir={omitir}
                      setOmitir={setOmitir}

                    />
                    :
                    <ContainerRegisterParticular3
                      setVerdadero2={setVerdadero2}
                      userCore={userCore}
                      setUserCore={setUserCore}
                      omitir={omitir}
                      setOmitir={setOmitir}

                    />
                )


          }
        </Layout>





        {/* {verdadero == false ?
        <ContainerRegisterParticular1
          setVerdadero={setVerdadero}
          userCore={userCore}
          setUserCore={setUserCore}
        />
        :
        (
          verdadero2 == false ?
            <ContainerRegisterParticular2
              setVerdadero={setVerdadero}
              setVerdadero2={setVerdadero2}
              userCore={userCore}
              setUserCore={setUserCore}
              omitir={omitir}
              setOmitir={setOmitir}
            />
            :
            <ContainerRegisterParticular3
              setVerdadero2={setVerdadero2}
              userCore={userCore}
              setUserCore={setUserCore}
              omitir={omitir}
              setOmitir={setOmitir}
            />
        )} */}

      </div>
    </div>
  )
}